[package]
name = "telemetry_calculator"
version = "0.1.0"
authors = ["thinkier <thinkier@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18"

[dependencies.piston_window]
version = "0.100"
optional = true

[dependencies.piston2d-graphics]
version = "*"
features = ["glyph_cache_rusttype"]
optional = true

[features]
smooth = []
visualize = ["piston_window", "piston2d-graphics"]

default = ["smooth", "visualize"]
