[package]
name = "telemetry_calculator"
version = "0.1.0"
authors = ["thinkier <thinkier@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18"

# Not gonna happen, gonna use nalgebra and let nalgebra take care of the messy vector calculus
[dependencies.packed_simd]
version = "0.3"
optional = true

[dependencies.piston_window]
version = "0.98"
optional = true

[features]
simd = ["packed_simd"]
smooth = []
visualize = ["piston_window"]

default = ["smooth", "visualize"]