[package]
name = "telemetry_calculator"
version = "0.1.0"
authors = ["thinkier <thinkier@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.packed_simd]
version = "0.3"
optional = true

[features]
simd = ["packed_simd"]